### ISSUE TITLE
code : command not found

### ISSUE THREAD

**Issue by dengaojian** [lxchuan12/open-in-editor#1]
本地运行终端是可以启动vsCode并打开文件，但是在浏览器vue -devtools中试图打开并没有成功

**Comment by ruochuan12** [comment]
> 本地运行终端是可以启动vsCode并打开文件，但是在浏览器vue -devtools中试图打开并没有成功

可以加我微信 ruochuan12 及时交流，解决你的问题。

>我目前组织了[每周一起学200行左右的源码共读](https://www.yuque.com/ruochuan12/topics/1)活动。
>[第1期就是这篇文章](https://www.yuque.com/ruochuan12/notice/p1)

**Comment by dengaojian** [comment]
后将 'code' 改成 'code-insiders' ，就可以实现了，与本地vsCode版本有些关系

**Comment by ruochuan12** [comment]
> 后将 'code' 改成 'code-insiders' ，就可以实现了，与本地vsCode版本有些关系

好的，解决了就好。
